version: '3'

services:

  frontend:
    build: front
    command: "npm start"
    ports:
      - "4567:3000"
    volumes:
      - ./front:/src-front
      - /src-front/node_modules

  backend:
    build: back
    command: "npm start"
    # Mas adelante esto se va a cambiar por expose, solo debería ser interno
    ports:
      - "5678:5678"
    depends_on:
      - db
    environment:
      - NODE_ENV=prod
      - MONGODB_URL=mongodb://db/jdb
    volumes:
      - /src-back/node_modules

  db:
    image: mongo:4.4 # ultima estable
    # Mas adelante esto se va a cambiar por expose, solo debería ser interno
    ports:
      - "27017:27017"
